BAH-2782 | Move trigger to build_publish_clinic_config_db workflow

diff --git a/.github/workflows/build_publish_clinic_config_db.yaml b/.github/workflows/build_publish_clinic_config_db.yaml
--- a/.github/workflows/build_publish_clinic_config_db.yaml
+++ b/.github/workflows/build_publish_clinic_config_db.yaml
@@ -35,6 +35,7 @@ jobs:
           file: demo/db-backups/1.0.0-lite/mysql5.7/Dockerfile
           push: true
           tags: bahmni/openmrs-db:mysql5.7-${{env.ARTIFACT_VERSION}},bahmni/openmrs-db:clinic-config-mysql5.7
+  
   mysql5-6:
     name: Build with MySQL5.6
     runs-on: ubuntu-latest
@@ -57,3 +58,25 @@ jobs:
           file: demo/db-backups/1.0.0-lite/mysql5.6/Dockerfile
           push: true
           tags: bahmni/openmrs-db:mysql5.6-${{env.ARTIFACT_VERSION}},bahmni/openmrs-db:clinic-config-mysql5.6
+  
+  trigger-workflow:
+    name: Trigger workflow to deploy to docker env
+    needs: 
+      - mysql5-6
+      - mysql5-7
+    runs-on: ubuntu-latest
+    env:
+      ORG_NAME: Bahmni
+      REPOSITORY_NAME: bahmni-docker
+      EVENT_TYPE: openmrs-db-publish-event
+    steps:
+      - name: Create repository_dispatch
+        run: |
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/dispatches -d '{"event_type":"'"${EVENT_TYPE}"'"}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
